base/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('punch/', views.punch, name='punch'),
    path('on_work/', views.on_work, name='on_work'),
    path('off_work/', views.off_work, name='off_work'),
    path('report/', views.report, name='report'),
]

task/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='task_index'),
    path('index/', views.index, name='task_index'),
    path('add/', views.task_add, name='task_add'),
    path('edit/', views.task_edit, name='task_edit'),
    path('do_edit/', views.do_edit, name='do_edit'),
    path('delete/', views.do_delete, name='do_delete'),
    path('complete/', views.task_complete, name='task_complete'),
    path('do_complete/', views.do_complete, name='do_complete'),
]

task/models.py
from django.db import models
from base.models import Emp
from django.contrib.postgres.fields import JSONField

# Create your models here.
class Task(models.Model):

    gender = (
        ('1', '仅本部门可见'),
        ('2', '公开'),
    )
    emp = models.ForeignKey(Emp, db_index=True, db_column='emp_id', on_delete=models.CASCADE)
    date = models.DateField(auto_now=True)
    title = models.CharField(max_length=100)
    secret_lv = models.CharField(max_length=1, choices=gender)
    completed = models.BooleanField(default=False)

class TaskDetail(models.Model):
    id = models.OneToOneField(Task, on_delete=models.CASCADE, db_column='id', primary_key=True)
    detail = models.TextField(null=True)
    feel = models.TextField(null=True)

task/forms.py
from django import forms


class TaskForm(forms.Form):
    title = forms.CharField(label='任务标题', max_length=100)
    secret_lv = forms.ChoiceField(label='保密等级', choices=(('1', '仅限本部门查看'), ('2', '所有人可查看')), initial='1')
    detail = forms.CharField(label='具体内容', strip=False, widget=forms.Textarea)
    completed = forms.BooleanField(label='是否完成')
    

task/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Task, TaskDetail
from datetime import datetime
from .forms import TaskForm
from django.db.models import Q


def index(request):
    if not request.session.get('id', None):
        return redirect("/login/")
    tasks = Task.objects.filter(emp_id=request.session['id']).order_by('-id')
    return render(request, 'task/index.html', {'request': request, 'form': TaskForm, 'tasks':tasks})

def task_add(request):
    if request.method == "POST":
        title = request.POST.get('title').strip()
        secret_lv = request.POST.get('secret_lv')
        detail = request.POST.get('detail')
        task = Task(emp_id=request.session['id'],
            title = title,
            secret_lv = secret_lv
        )
        task.save()
        task_detail = TaskDetail(
            id = task,
            detail = detail
        )
        task_detail.save()
        return redirect("/task/add/")
    return render(request, 'task/add.html', {'request': request, 'form': TaskForm})

def task_edit(request):
    if request.method == "POST":
        task_id = request.POST.get('task_id')
        task = Task.objects.filter(id=task_id).first()
        return render(request, 'task/edit.html', {'request': request, 'task': task})
    return redirect("/task/")

def task_complete(request):
    if request.method == "POST":
        task_id = request.POST.get('task_id')
        task = Task.objects.filter(id=task_id).first()
        return render(request, 'task/complete.html', {'request': request, 'task': task})
    return redirect("/")

def do_edit(request):
    if request.method == "POST":
        task_id = request.POST.get('task_id')
        title = request.POST.get('title').strip()
        secret_lv = request.POST.get('secret_lv')
        detail = request.POST.get('detail')
        feel = request.POST.get('feel')

        task = Task.objects.filter(id=task_id).first()
        task_detail = TaskDetail.objects.filter(id=task).first()
        task.title = title
        task.secret_lv = secret_lv
        task.save()

        if feel:
            task_detail.feel = feel
        task_detail.detail = detail
        task_detail.save()
        return redirect("/task/")
    return redirect("/task/")

def do_delete(request):
    if request.method == "POST":
        task_id = request.POST.get('task_id')
        Task.objects.filter(id=task_id).delete()
        return redirect("/task/")
    return redirect("/task/")

def do_complete(request):
    if request.method == "POST":
        task_id = request.POST.get('task_id')
        feel = request.POST.get('feel')
        task = Task.objects.filter(id=task_id).first()
        task.completed = True
        task.save()
        task_detail = TaskDetail.objects.filter(id=task).first()
        task_detail.feel = feel
        task_detail.save()
    return redirect("/")

templates/task/add.html
<!doctype html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- 上述meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/base/css/index.css">
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    
    <title>添加任务</title>
</head>
<body>
    
    <div class="container">
        <div class="col">
            <!-- <a href="/login/logout/" class="text-success " ><ins>退出</ins></a><br> -->
            
            <h3 class="float-right text-primary">{{ request.session.name }}</h3>
            <h3 class="float-right text-muted">{{ request.session.dept_name }}：</h3>

            <hr>
            
            <ul class="nav nav-pills" role="tablist">
                <li><a href="/base/">首页</a></li>
                <li><a href="/base/punch/">打卡</a></li>
                <li><a href="/base/report/">考勤表</a></li>
                <li><a href="/task/">任务中心</a></li>
                <li class="active"><a href="/task/add/">添加任务</a></li>
            </ul>
            
            <hr>

            <div>
                <h3>添加任务</h3>
                <form action="/task/add/" method="POST" role="form">
                    {% csrf_token %}
                    <div class="form-group">
                        任务标题
                        <input type="text" name="title" maxlength="100" required="" id="id_title" class="form-control"">
                    </div>
                    <div>保密等级
                        <select name="secret_lv" id="id_secret_lv" value="1">
                            <option value="1" selected="">仅限本部门查看</option>
                            <option value="2">所有人可查看</option>
                        </select>
                    </div>
                    <div>
                        具体内容
                        <textarea name="detail" class="form-control" rows="6" required="" id="id_detail"></textarea>
                    </div>
                    <button type="submit" class="btn btn-success float-right">保存</button>
                </form>
                <a href="/task/"><button class="btn btn-primary float-right">取消</button></a>
            </div>
            
            <hr>

            
        </div>
    </div> <!-- /container -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.15.0/umd/popper.js"></script>
    <script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="/static/login/js/login.js"></script>    

</body>
</html>

templates/task/complete.html
<!doctype html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- 上述meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/base/css/index.css">
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    
    <title>添加任务</title>
</head>
<body>
    
    <div class="container">
        <div class="col">
            <!-- <a href="/login/logout/" class="text-success " ><ins>退出</ins></a><br> -->
            
            <h3 class="float-right text-primary">{{ request.session.name }}</h3>
            <h3 class="float-right text-muted">{{ request.session.dept_name }}：</h3>

            <hr>
            
            <ul class="nav nav-pills" role="tablist">
                <li><a href="/base/">首页</a></li>
                <li><a href="/base/punch/">打卡</a></li>
                <li><a href="/base/report/">考勤表</a></li>
                <li class="active"><a href="/task/">任务中心</a></li>
                <li><a href="/task/add/">添加任务</a></li>
            </ul>

            <hr>

            <div>
                <h3>完成任务</h3>
                <form action="/task/do_complete/" method="POST" role="form">
                    {% csrf_token %}
                    {{ task.title }}
                    <br>
                    <textarea class="form-control" style="background-color:white" rows="3" readonly="value">{{ task.taskdetail.detail }}</textarea>
                    写下完成该任务时的感想
                    <textarea name="feel" class="form-control" rows="6" required="" id="id_detail"></textarea>
                    <input type="hidden" value="{{ task.id }}" name="task_id">
                    <button type="submit" class="btn btn-success float-right">提交</button>
                    
                </form>
                <a href="/"><button class="btn btn-primary float-right">取消</button></a>
            </div>
            
            <hr>

            
        </div>
    </div> <!-- /container -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.15.0/umd/popper.js"></script>
    <script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="/static/login/js/login.js"></script>    

</body>
</html>

templates/task/edit.html
<!doctype html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- 上述meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/base/css/index.css">
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    
    <title>添加任务</title>
</head>
<body>
    
    <div class="container">
        <div class="col">
            <!-- <a href="/login/logout/" class="text-success " ><ins>退出</ins></a><br> -->
            
            <h3 class="float-right text-primary">{{ request.session.name }}</h3>
            <h3 class="float-right text-muted">{{ request.session.dept_name }}：</h3>

            <hr>
            
            <ul class="nav nav-pills" role="tablist">
                <li><a href="/base/">首页</a></li>
                <li><a href="/base/punch/">打卡</a></li>
                <li><a href="/base/report/">考勤表</a></li>
                <li class="active"><a href="/task/">任务中心</a></li>
                <li><a href="/task/add/">添加任务</a></li>
            </ul>

            <hr>

            <div>
                <h3>编辑任务</h3>
                <form action="/task/do_edit/" method="POST" role="form">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name">任务标题</label>
                        <input type="text" name="title" maxlength="100" required="" id="id_title" class="form-control" value="{{ task.title }}">
                    </div>
                    <div>保密等级
                        <select name="secret_lv" id="id_secret_lv" value="{{ task.secret_lv }}">
                            <option value="1" selected="">仅限本部门查看</option>
                            <option value="2">所有人可查看</option>
                        </select>
                    </div>
                    <div>
                        具体内容
                        <textarea name="detail" class="form-control" rows="6" required="" id="id_detail">{{ task.taskdetail.detail }}</textarea>
                    </div>
                    
                    {% if task.completed %}
                    <div>
                        感受
                        <textarea name="feel" class="form-control" rows="6" required="" id="id_detail">{{ task.taskdetail.feel }}</textarea>
                    </div>
                    {% endif %}

                    <input type="hidden" value="{{ task.id }}" name="task_id">
                    <button type="submit" class="btn btn-success float-right">保存</button>
                </form>
                <a href="/task/"><button class="btn btn-primary float-right">取消</button></a>
            </div>
            
            <hr>

            
        </div>
    </div> <!-- /container -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.15.0/umd/popper.js"></script>
    <script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="/static/login/js/login.js"></script>    

</body>
</html>

templates/task/index.html
<!doctype html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- 上述meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/base/css/index.css">
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    
    <title>任务</title>
</head>
<body>
    
    <div class="container">
        <div class="col">
            <!-- <a href="/login/logout/" class="text-success " ><ins>退出</ins></a><br> -->
            
            <h3 class="float-right text-primary">{{ request.session.name }}</h3>
            <h3 class="float-right text-muted">{{ request.session.dept_name }}：</h3>

            <hr>
            
            <ul class="nav nav-pills" role="tablist">
                <li><a href="/base/">首页</a></li>
                <li><a href="/base/punch/">打卡</a></li>
                <li><a href="/base/report/">考勤表</a></li>
                <li class="active"><a href="/task/">任务中心</a></li>
                <li><a href="/task/add/">添加任务</a></li>
            </ul>

            <hr>
            
            <div>
                <table class="table table-condensed">
                    <!-- <caption>精简表格布局</caption> -->
                    <thead>
                        <tr>
                            <th>标题</th>
                            <th>内容</th>
                            <th>是否完成</th>
                            <th>操作</th>
                            <th>日期</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in tasks %}
                        <tr>
                          <td>
                            {{ task.title }}
                          </td>

                          <td>
                              <textarea class="form-control" style="background-color:white" rows="3" readonly="value">{{ task.taskdetail.detail }}</textarea>
                          </td>

                          <td>
                            {% if task.completed %}
                            <textarea class="form-control" style="background-color:white" rows="3" readonly="value">{{ task.taskdetail.feel }}</textarea>
                            {% else %}
                            未完成
                            {% endif %}
                          </td>

                          <td>
                            <form method="POST">
                                {% csrf_token %}
                                <input type="hidden" value="{{ task.id }}" name="task_id">
                                <button type="submit" class="btn btn-primary" formaction="/task/edit/">编辑</button>
                                <button type="submit" class="btn btn-danger" formaction="/task/delete/">删除</button>
                            </form>
                          </td>

                          <td>
                              {{ task.date }}
                          </td>
                        </tr>
                        {% endfor %}
                        
                    </tbody>
                </table>
                <!-- <div>当前任务</div>
                {% for task in tasks %}
                <div>
                    
                    任务：{{ task.title }}
                    内容：{{ task.taskdetail.detail }}
                    <form method="POST">
                        {% csrf_token %}
                        <input type="hidden" value="{{ task.id }}" name="task_id">
                        <button type="submit" formaction="/task/edit/">编辑</button>
                        <button type="submit" formaction="/task/delete/">删除</button>
                    </form>
                </div>
                {% endfor %} -->
            </div>
            
            <hr>

            
        </div>
    </div> <!-- /container -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.15.0/umd/popper.js"></script>
    <script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="/static/login/js/login.js"></script>    

</body>
</html>